<?php

$module = array( '5bbaf629df26e' => array(
    'key'        => '5bbaf629df26e',
    'name'       => 'kpi',
    'label'      => 'KPI',
    'display'    => 'block',
    'sub_fields' => array(
        array(
            'key'               => 'field_5bbaf65f6ecbe',
            'label'             => 'Module Description',
            'name'              => 'module_description',
            'type'              => 'textarea',
            'instructions'      => 'Max Characters: 280',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '70%',
                'class' => '',
                'id'    => '',
            ),
            'default_value'     => '',
            'placeholder'       => '',
            'maxlength'         => 280,
            'rows'              => '3',
            'new_lines'         => 'br',
        ),
        array(
            'key'               => 'field_5bbaf7676ecc3',
            'label'             => 'Background Image',
            'name'              => 'background_image',
            'type'              => 'image',
            'instructions'      => 'Recommended size 1465 x 335',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '30%',
                'class' => '',
                'id'    => '',
            ),
            'return_format'     => 'id',
            'preview_size'      => 'thumbnail',
            'library'           => 'all',
            'mime_types'        => 'svg,png,jpg,webp',
        ),
        array(
            'key'               => 'field_5bbaf6befecc0',
            'label'             => 'Symbol Before KPI',
            'name'              => 'kpi_symbol_before',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '25',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 1,
        ),
        array(
            'key'               => 'field_5bbaf6bd6ecbf',
            'label'             => 'KPI Number',
            'name'              => 'kpi_number',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '25',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 3,
        ),
        array(
            'key'               => 'field_5bsep6bd6ecbf',
            'label'             => 'KPI Separator',
            'name'              => 'kpi_separator',
            'type'              => 'select',
            'instructions'      => 'Choose an option from the dropdown.',
            'choices'           => array(
                'ampersand' => '&',
                'comma'     => ',',
                'dash'      => '-',
                'colon'     => ':',
                'pipe'      => '|',
                'slash'     => '/',
                'equal'     => '=',
                'plus'      => '+',
            ),
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '25',
                'class' => '',
                'id'    => '',
            ),
            'placeholder'       => 'Select an option',
            'default_value'     => '',
            'return_format'     => 'label',
            'maxlength'         => 1,
            'allow_null'        => 1,
            'multiple'          => 0,
        ),
        array(
            'key'               => 'field_5bbaf6bdadibf',
            'label'             => 'KPI Number Additional',
            'name'              => 'kpi_number_additional',
            'type'              => 'number',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '25',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 3,
        ),
        array(
            'key'               => 'field_5bbaf6f46ecc0',
            'label'             => 'Symbol After KPI',
            'name'              => 'kpi_symbol_after',
            'type'              => 'text',
            'instructions'      => '',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '33',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 3,
        ),
        array(
            'key'               => 'field_5bbaf7176ecc1',
            'label'             => 'KPI Title',
            'name'              => 'kpi_title',
            'type'              => 'text',
            'instructions'      => 'Title that appears under KPI number.',
            'required'          => 1,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '33',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 56,
        ),
        array(
            'key'               => 'field_5bbaf72f6ecc2',
            'label'             => 'KPI Description',
            'name'              => 'kpi_description',
            'type'              => 'text',
            'instructions'      => 'Small description that appears under KPI and title.',
            'required'          => 0,
            'conditional_logic' => 0,
            'wrapper'           => array(
                'width' => '33',
                'class' => '',
                'id'    => '',
            ),
            'maxlength'         => 56,
        ),
    ),
) );

return $module;
